package myitcv_io

import (
	"html/template"
	"net/http"
	"path"
	"strings"
)

type pkg struct {
	ImportPath   string
	RelPath      string
	GithubPath   string
	WikiUrl      string
	Desc         string
	MonoRepo     bool
	TestMonoRepo bool
}

var ps = []pkg{
	pkg{
		RelPath:    "gopherize.me",
		GithubPath: "github.com/myitcv/gopherize.me",
		Desc:       "GopherJS React version of Gopherize.me",
	},
	pkg{
		RelPath:    "react",
		GithubPath: "github.com/myitcv/react",
		WikiUrl:    "https://github.com/myitcv/react/wiki",
		Desc:       "Package react is a set of GopherJS bindings for Facebook's React, a Javascript library for building user interfaces.",
	},
	pkg{
		RelPath:    "remarkable",
		GithubPath: "github.com/myitcv/remarkable",
		Desc:       "Package remarkable provides an incomplete wrapper for remarkable (https://github.com/jonschlinkert/remarkable), a pure Javascript markdown parser",
	},
	pkg{
		RelPath:    "highlightjs",
		GithubPath: "github.com/myitcv/highlightjs",
		Desc:       "Package highlightjs provides an incomplete wrapper for Highlight.js (https://github.com/isagalaev/highlight.js), a Javascript syntax highlighter",
	},
	pkg{
		RelPath:    "immutable",
		GithubPath: "github.com/myitcv/immutable",
		Desc:       "Package immutable is a helper package for the immutable data structures generated by myitcv.io/immutable/cmd/immutableGen.",
	},
	pkg{
		RelPath:    "gogenerate",
		GithubPath: "github.com/myitcv/gogenerate",
		Desc:       "Package gogenerate exposes some of the unexported internals of the go generate command as a convenience for the authors of go generate generators.  See https://github.com/myitcv/gogenerate/wiki/Go-Generate-Notes for further notes on such generators. It also exposes some convenience functions that might be useful to authors of generators",
	},
	pkg{
		RelPath:    "sorter",
		GithubPath: "github.com/myitcv/sorter",
	},
	pkg{
		RelPath:    "go",
		GithubPath: "github.com/myitcv/go",
		Desc:       "go is a wrapper around the go tool that automatically sets the GOPATH env variable based on the process' current directory.",
	},
	pkg{
		RelPath:    "gg",
		GithubPath: "github.com/myitcv/gg",
	},
	pkg{
		RelPath:    "gjbt",
		GithubPath: "github.com/myitcv/gjbt",
		Desc:       "gjbt is a simple (temporary) wrapper for GopherJS to run tests in Chrome as opposed to NodeJS. It should be considered to be a direct replacement for gopherjs test",
	},
	pkg{
		RelPath:    "gai",
		GithubPath: "github.com/myitcv/gai",
	},
	pkg{
		RelPath:    "gitgodoc",
		GithubPath: "github.com/myitcv/gitgodoc",
		Desc:       "gitgodoc allows you to view godoc documentation for different branches of a Git repository",
	},
	pkg{
		RelPath:    "g",
		GithubPath: "github.com/myitcv/g",
	},
}

func init() {
	pkgs := make(map[string]pkg, len(ps))

	for _, v := range ps {
		v.ImportPath = path.Join("myitcv.io", v.RelPath)
		pkgs[v.RelPath] = v
	}

	http.HandleFunc("/", func(w http.ResponseWriter, req *http.Request) {
		p := strings.TrimPrefix(req.URL.EscapedPath(), "/")
		ps := strings.Split(p, "/")

		if p == "" {
			// root
			tmpls.ExecuteTemplate(w, "root", pkgs)
		} else if r, ok := pkgs[ps[0]]; ok {
			tmpls.ExecuteTemplate(w, "pkg", r)
		} else if p == "blah" {
			tmpls.ExecuteTemplate(w, "blah", pkg{
				ImportPath: path.Join("myitcv.io", p),
			})
		} else if p == "blah2" {
			tmpls.ExecuteTemplate(w, "blah2", pkg{
				ImportPath: path.Join("myitcv.io", p),
			})
		} else {
			// mono repo
			tmpls.ExecuteTemplate(w, "mono", pkg{
				ImportPath: path.Join("myitcv.io", p),
			})
		}
	})
}

// copied from Go 1.8.1 std lib
func stripPort(hostport string) string {
	colon := strings.IndexByte(hostport, ':')
	if colon == -1 {
		return hostport
	}
	if i := strings.IndexByte(hostport, ']'); i != -1 {
		return strings.TrimPrefix(hostport[:i], "[")
	}
	return hostport[:colon]
}

var tmpls = template.Must(template.New("tmpls").Parse(`
{{define "blah2"}}
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
	<meta name="go-import" content="myitcv.io git https://github.com/myitcv/x">
	<meta name="go-import" content="{{.ImportPath}} mod https://raw.githubusercontent.com/myitcv/pubx/master">
	<meta name="go-source" content="myitcv.io https://github.com/myitcv/x/wiki https://github.com/myitcv/x/tree/master{/dir} https://github.com/myitcv/x/blob/master{/dir}/{file}#L{line}">
	<meta http-equiv="refresh" content="0; url=https://godoc.org/{{.ImportPath}}">
</head>
<body>
Redirecting to docs at <a href="https://godoc.org/{{.ImportPath}}">godoc.org/{{.ImportPath}}</a>...
</body>
</html>
{{end}}

{{define "blah"}}
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
	<meta name="go-import" content="myitcv.io git https://github.com/myitcv/x">
	<meta name="go-source" content="myitcv.io https://github.com/myitcv/x/wiki https://github.com/myitcv/x/tree/master{/dir} https://github.com/myitcv/x/blob/master{/dir}/{file}#L{line}">
	<meta http-equiv="refresh" content="0; url=https://godoc.org/{{.ImportPath}}">
</head>
<body>
Redirecting to docs at <a href="https://godoc.org/{{.ImportPath}}">godoc.org/{{.ImportPath}}</a>...
</body>
</html>
{{end}}

{{define "mono"}}
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
	<meta name="go-import" content="myitcv.io git https://github.com/myitcv/x">
	<!--<meta name="go-import" content="{{.ImportPath}} mod https://raw.githubusercontent.com/myitcv/pubx/master">-->
	<meta name="go-source" content="myitcv.io https://github.com/myitcv/x/wiki https://github.com/myitcv/x/tree/master{/dir} https://github.com/myitcv/x/blob/master{/dir}/{file}#L{line}">
	<meta http-equiv="refresh" content="0; url=https://godoc.org/{{.ImportPath}}">
</head>
<body>
Redirecting to docs at <a href="https://godoc.org/{{.ImportPath}}">godoc.org/{{.ImportPath}}</a>...
</body>
</html>
{{end}}

{{define "pkg"}}
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{.ImportPath}}</title>
	 {{if .MonoRepo -}}
    <meta name="go-import" content="myitcv.io git https://github.com/myitcv/x">
    <meta name="go-import" content="{{.ImportPath}} mod https://raw.githubusercontent.com/myitcv/pubx/master">
	 {{else if .TestMonoRepo -}}
    <meta name="go-import" content="myitcv.io git https://github.com/myitcv/y">
	 {{else -}}
    <meta name="go-import" content="{{.ImportPath}} git https://{{.GithubPath}}">
	 {{end}}
  </head>
  <body>
  <p>
    <h3><code>{{.ImportPath}}</code></h3>
	 <p>{{.Desc}}</p>
	 <code>go get -u {{.ImportPath}}</code><br/><br/>
	 {{if .WikiUrl}}
    <a href="{{.WikiUrl}}">Wiki</a><br/>
	 {{end}}
    <a href="https://godoc.org/{{.ImportPath}}"><code>godoc</code></a><br/>
	 {{if .MonoRepo -}}
    <a href="https://github.com/myitcv/x/tree/master/{{.RelPath}}">Source</a>
	 {{else if .TestMonoRepo -}}
    <a href="https://github.com/myitcv/y/tree/master/{{.RelPath}}">Source</a>
	 {{else -}}
    <a href="https://{{.GithubPath}}">Source</a>
	 {{end}}
  </p>
	 {{template "footer"}}
  </body>
</html>
{{end}}

{{define "root"}}
<!DOCTYPE html>
<html>
  <head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>myitcv.io</title>
  <meta name="go-import" content="myitcv.io git https://github.com/myitcv/x">
  </head>
  <body>
  <h3><code>myitcv.io</code></h3>
  <p>
  <a href="http://blog.myitcv.org.uk">Blog</a><br/>
  <a href="https://twitter.com/_myitcv">Twitter</a>
  </p>
  <ul style="list-style: none; padding-left:0;">
  <li>Packages: <ul>
  {{range .}}
  <li><a href="/{{.RelPath}}">{{.ImportPath}}</a></li>
  {{end}}
  </ul>
  </li></ul>
	{{template "footer"}}
  </body>
</html>
{{end}}

{{define "footer"}}
<br/>
<hr style="border-width: 1px 1px 0;
           border-style: solid;
           border-color: darkgray;"/>
<span style="font-size:smaller">
<em>
<a href="mailto:paul@myitcv.io">paul@myitcv.io</a><br/>
<a href="/">Home</a>
</em>
</span>
{{end}}
`))
